### ISSUE TITLE
The "Obsidian open" command doesn't open my note in the Obsidian app

### ISSUE THREAD

**Issue by korkota** [obsidian-nvim/obsidian.nvim#268]
### 🐛 Describe the bug

**Actual result:** 
1. Open a note.
2. Run the "Obsidian open" command.
3. The note isn't open in the Obsidian app.

**Expected result:**
3. The note is open in the Obsidian app.

**Additional info:**
1. I can run `vim.ui.open("obsidian://open?vault=korkota&file=drafts%2FMarksman")` and open my note in the Obsidian app.
2. I see no errors when run `:messages` or `:NoiceAll` commands.

### Config

https://github.com/korkota/dotfiles/blob/main/.config/nvim/lua/plugins/obsidian.lua

### Environment

```
==============================================================================
obsidian:                                   require("obsidian.health").check()

- ✅ OK neovim >= 0.11

obsidian.nvim [Version] ~
- ✅ OK Obsidian.nvim v3.12.0 (2f0222b3eb20382cadf3e1d91f368318b768771c)

obsidian.nvim [Pickers] ~
- ✅ OK ✓ fzf-lua: 9a4b8011f1bab6c54d78553ac6fb207d6a85287f
- ✅ OK ✓ snacks.nvim: bc0630e43be5699bb94dadc302c0d21615421d93

obsidian.nvim [Completion] ~
- ✅ OK ✓ blink.cmp: 9bcb14b43852a6f2bfd5ac9ef29cb5cf09b1b39b

obsidian.nvim [Dependencies] ~
- ✅ OK ✓ rg: ripgrep 14.1.0
- ✅ OK ✓ plenary.nvim: 857c5ac632080dba10aae49dba902ce3abf91b35


```

**Comment by neo451** [comment]
do you use version = "*"? this should be fixed on the main @korkota

**Comment by korkota** [comment]
> do you use version = "*"? this should be fixed on the main [@korkota](https://github.com/korkota)

![Image](https://github.com/user-attachments/assets/05b9d0aa-64e4-4db6-b29d-654f1c1958f0)

**Comment by neo451** [comment]
ah  yes, you can comment out the version = "*" line, which make you use a tagged release, which has this bug. @korkota

**Comment by bhannawa** [comment]
This issue is still not resolved for me on the latest commit (it was also present on d22a3b5 btw). I suspect it would be an issue with WSL2, since Obsidian is in Windows 11. I have wsl-open installed.

Only bothersome because this feature worked before I switch from the epwlash version. Not sure if I am doing something wrong, but just want to put this out there.

**Comment by neo451** [comment]
try putting set `open.func` as `print` to get the uri it gets, and try open that uri with `wsl-open`. and tell me the results @bhannawa

**Comment by bhannawa** [comment]
The uri it gets is: "obsidian://open?vault=ABC%20Vault&file=SECRET/PRIVATE.md"

I open a new terminal and type "wsl-open obsidian://open?vault=ABC%20Vault&file=SECRET/PRIVATE.md" I get the following output:
<img width="2028" height="116" alt="Image" src="https://github.com/user-attachments/assets/cdb92280-6661-42a2-aa76-0af3f0111c68" />

The obsidian window opens but only to the new tab screen. The file itself doesn't open up.

EDIT: I just created a blank vault with no plugins to try this again. Same results as above. Also tested advanced-uri true vs false, and same results.

EDIT 2: POSITIVE Note! Found out if I run the wsl-open command with quotes around the uri then it opens properly. Without quotes, it opens obsidian to the new tab screen. So the way to open obsidian to note with wsl-open is:
`wsl-open "obsidian://open?vault=ABC%20Vault&file=SECRET/PRIVATE.md"`

Will try to figure out how to modify the open command to accommodate this, unless you can figure out how to do it first.

**Comment by bhannawa** [comment]
Ok. There is probably a more elegant way to implement this, but this is a quick and dirty way to get this working with wsl-open. 

Create a function like so:
```
--- Sets how you follow URLs
---@param url string
local wsl_open = function(url)
  vim.ui.open(url, { cmd = { 'wsl-open' } })
end
```

Then in obsidian.config.OpenOpts section, set `func = wsl_open,`

Works for me perfectly!

**Comment by neo451** [comment]
@bhannawa which linux distro are you using? and does your `gx` work? I recently set up `wsl-archlinux` to have a try, and gx don't work, which is caused by `vim.ui.open` as well.

I replace the old repo's complex os specific logic of determining which open program to use (which used `wsl-open`), in hope that neovim's `vim.ui.open` is more reliable and can handle more edge cases.

But looking at the actual implementation, `vim.ui.open` only checks for `wslview`, which is an archived project: https://github.com/wslutilities/wslu and if you confirm I am understanding these all correctly, and your `gx` don't work either, I think this issue should be reflected to neovim's repo, and I can PR there to properly fix this.

for now your solution works nicely, and I prefer this below so that my `gx` works as well:

```lua
local old_open = vim.ui.open

vim.ui.open = function(uri, opts)
  opts = opts or { cmd = { "wsl-open" } }
  old_open(uri, opts)
end
```

**Comment by bhannawa** [comment]
@neo451 So sorry this fell off my radar. I am running AlmaLinux 9 in WSL2. My `gx` actually tries to use `xdg-open` it looks like based on this screenshot:
<img width="1091" height="69" alt="Image" src="https://github.com/user-attachments/assets/86c2b29a-ccd6-4911-97ac-4e8e8a5dd2cc" />

I'm in the middle of a project right now and have something working, so I will have to try your cleaner implementation when I get a chance. I will try to pay attention to this thread and reply if it helps at all. Would be super cool to help get something fixed in neovim :)

**Comment by bhannawa** [comment]
Okay so after looking into the responses on that thread (https://github.com/neovim/neovim/issues/34970), I started playing with xdg-open a little bit to understand the issue. It seems like neovim is not interested in changing what they are doing, and that sort of makes sense to leave it more general.

I looked into wsl-open because it has just worked so well for me compared to messing with xdg-open itself, and I noticed a command on the wsl-open readme about adding it to xdg-open. There is a flag (-w) built into wsl-open that adds a few lines to your .bashrc that seem to make the default obsidian.nvim config work for `:Obsidian open` as expected and leave `gx` command working as well.

So even though I had something in my config that worked, this seems like a cleaner solution to me. Just updating here in case anyone is looking in the future. Simply open a terminal and run in `wsl-open -w` and source your .bashrc (or re-start the shell).
