### ISSUE TITLE
Tag search includes section links and other non-tags

### ISSUE THREAD

**Issue by thiskurt** [obsidian-nvim/obsidian.nvim#405]
### 🐛 Describe the bug

When using the tag search with `:obsidian tags` it will return several things that aren't really tags, but do contain `#abc`.

The biggest issue for me personally is that links to sections with `[[#section]]` or `[[file#section]]` or external links that happen to contain a `#` like `[site](https://site.example/link#withthis)` show up here too. The bulk of the 'tags' that show up in the search are actually section links.

I'm assuming the tags are just found with a grep search? I don't know if it would be possible to exclude these specific cases from showing up as tags.

All the cases I've had where something came up as a tag where it really wasnt:

- Links to sections
- Wrapped in code quotes `#LikeThis`
- Inside html comments `<!-- #example -->`
- Inside code blocks

### Config

```
return {
	"obsidian-nvim/obsidian.nvim",
	version = "*",
	lazy = true,
	ft = "markdown",
	dependencies = {
		"nvim-lua/plenary.nvim",
	},

	config = function ()
		-- === Options ===
		require('obsidian').setup({
			legacy_commands = false,
			prefered_link_style = "wiki",
			workspaces = {
				{
					name = "Tracking",
					path = "~/Tracking",
				},
			},
			--new_notes_location = "00 Inbox",
			daily_notes = {
				folder = "21 Daily Notes",
				date_format = "%Y-%m-%d",
				default_tags = { "daily" },
			},
			ui = {
				enable = false, -- Disabling this to work with render-markdown
			},
			templates = {
				folder = ".templates",
				note_id_func = function(title)
					return title
				end,
				-- Custom {{substitution}} strings
				substitutions = {
					year_month = function()
						return tostring(os.date("%Y-%m", os.time()))
					end,
				},
				-- Per template customizations; must match title
				customizations = {
					daily = { notes_subdir = "21 Daily Notes" },
				},
			},
			completion = {
				nvim_cmp  = false,
				blink     = true,
				min_chars = 2,
			},
			-- --- Frontmatter ---
			---@return table
			note_frontmatter_func = function(note)
				local out
				-- `note.metadata` contains any manually added fields in the frontmatter.
				-- So here we just make sure those fields are kept in the frontmatter.
				if note.metadata ~= nil and not vim.tbl_isempty(note.metadata) then
				  for k, v in pairs(note.metadata) do
					out[k] = v
				  end
				end

				return out
			end,
		})

		-- === Keymaps ===
		vim.keymap.set('n', '<leader>oc', '<cmd>Obsidian<CR>',                   { desc = '[O]bsidian [C]ommands'} )
		vim.keymap.set('n', '<leader>ob', '<cmd>Obsidian backlinks<CR>',         { desc = '[O]bsidian [B]acklinks'})
		vim.keymap.set('n', '<leader>ol', '<cmd>Obsidian links<CR>',             { desc = '[O]bsidian [L]inks'})
		vim.keymap.set('n', '<leader>od', '<cmd>Obsidian dailies<CR>',           { desc = '[O]bsidian [D]ailies'})
		vim.keymap.set('n', '<leader>on', '<cmd>Obsidian new<CR>',               { desc = '[O]bsidian [N]ew Note'})
		vim.keymap.set('n', '<leader>ot', '<cmd>Obsidian new_from_template<CR>', { desc = '[O]bsidian New from [T]emplate'})
		vim.keymap.set('n', '<leader>oT', '<cmd>Obsidian tags<CR>',              { desc = '[O]bsidian [T]ags'})
		vim.keymap.set('n', '<leader>oi', '<cmd>Obsidian toc<CR>',	             { desc = '[O]bsidian toc'})
	end,
}

```

### Environment

```

==============================================================================
obsidian:                                                                   ✅

- ✅ OK neovim >= 0.11

obsidian.nvim [Version] ~
- ✅ OK obsidian.nvim v3.13.0 (705cc9b4f66eca1e54040ac819102e80a32896d3)

obsidian.nvim [Environment] ~
- ✅ OK operating system: Darwin

obsidian.nvim [Config] ~
- ✅ OK • dir: /Users/kurt/Dropbox/Tracking-Mac

obsidian.nvim [Pickers] ~
- ✅ OK telescope.nvim: b4da76be54691e854d3e0e02c36b0245f945c2c7
- ✅ OK mini.nvim: 7bbafa4691147bc8b74a51986b957daca14c1876

obsidian.nvim [Completion] ~
- ✅ OK blink.cmp: bae4bae0eedd1fa55f34b685862e94a222d5c6f8

obsidian.nvim [Dependencies] ~
- ✅ OK rg: 14.1.1

```

**Comment by neo451** [comment]
yes, know issue, there has been an attempt to solve this in the past, but has been reverted. #206  
I think time is ripe for a another try, since people raise this one a lot.

**Comment by neo451** [comment]
@thiskurt I pushed a small change, turns out I was overthinking the problem before, try it to see what cases I am missing.

**Comment by thiskurt** [comment]
@neo451 I looked for a previous issue regarding this, but I must've missed this one.

I just updated the plugin on my system, and yes all the section links that were cluttering up the tags are now gone. 

Looks like a `#` in a HTML comment will still show up as a tag, though. `<!-- #region -->` will register as tag `#region`

That's the only case I can see.

Thanks.

**Comment by neo451** [comment]
should be resolved on the main :)

**Comment by thiskurt** [comment]
Yep, didn't see any other issues this time.
